"""Data models for the backend."""

from .action import (
    ActionRequest,
    ActionResponse,
    ActionType,
    AttackDetail,
    CheckDetail,
    DamageDetail,
    Effect,
    Outcome,
    ResolutionType,
    SavingThrowDetail,
)
from .character import (
    AbilityScores,
    Character,
    CharacterClass,
    Equipment,
    Skill,
    SkillDefinition,
)
from .module import (
    ActiveModule,
    Module,
    ModuleMetadata,
    ModuleNPC,
    ModuleScene,
    ModuleSummary,
    Quest,
    QuestObjective,
    QuestStatus,
    StoryNode,
    StoryNodeTransition,
    Trigger,
    TriggerAction,
    TriggerCondition,
    TriggerType,
)
from .state import (
    Actor,
    BootstrapState,
    CharacterCard,
    CharacterCreateRequest,
    CharacterSkill,
    ClassFeatures,
    GamePhase,
    HP,
    NarrativeHistoryEntry,
    Scene,
)

__all__ = [
    # Action models
    "ActionRequest",
    "ActionResponse",
    "ActionType",
    "AttackDetail",
    "CheckDetail",
    "DamageDetail",
    "Effect",
    "Outcome",
    "ResolutionType",
    "SavingThrowDetail",
    # Character models
    "AbilityScores",
    "Character",
    "CharacterClass",
    "Equipment",
    "Skill",
    "SkillDefinition",
    # Module models
    "ActiveModule",
    "Module",
    "ModuleMetadata",
    "ModuleNPC",
    "ModuleScene",
    "ModuleSummary",
    "Quest",
    "QuestObjective",
    "QuestStatus",
    "StoryNode",
    "StoryNodeTransition",
    "Trigger",
    "TriggerAction",
    "TriggerCondition",
    "TriggerType",
    # State models
    "Actor",
    "BootstrapState",
    "CharacterCard",
    "CharacterCreateRequest",
    "CharacterSkill",
    "ClassFeatures",
    "GamePhase",
    "HP",
    "NarrativeHistoryEntry",
    "Scene",
]
